myfind: myfind.c File Reference
myfind.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <errno.h>
#include <assert.h>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <sys/queue.h>
Classes
struct Args
The command line arguments provided to the application at startup.
struct FileNode
A single node in the linked list of file names.
Enumerations
enum FileTypes {
None = 0, BlockSpecialFile = 1 << 0, CharacterSpecialFile = 1 << 1, Directory = 1 << 2,
NamedPipe = 1 << 3, RegularFile = 1 << 4, SymbolicLink = 1 << 5, Socket = 1 << 6
}
Contains flags indicating the file types to be printed in the application's output.
Functions
void PrintUsage ()
Prints an explanation of the application's command line arguments.
bool ParseCommandLineArgs (char *argv[], struct Args *args)
bool ConvertToInteger (char *s, int *i)
bool QueryUserID (char *userName, int *userID)
bool ParseFileTypes (char *fileTypeChars, enum FileTypes *fileTypes)
void SearchFile (char *file_name, struct Args *args)
void SearchDirectory (char *dir_name, struct Args *args)
char * CombinePath (char *path1, char *path2)
struct FileNode * AddListNode (struct FileNode **head, char *fileName)
void FreeList (struct FileNode **head)
bool ShouldPrintFileInformation (char *filePath, struct stat *fileInformation, struct Args *args)
void PrintFileInformation (char *filePath, struct stat *fileInformation, struct Args *args)
int main (int argc, char *argv[])
Detailed Description
myfind - A simplified version of the "find" utility provided by the Linux shell.
Author:
Alexander Feldinger <ic17b055@technikum-wien.at>
Thomas Haberl <ic17b021@technikum-wien.at>
Michael Zajac <ic17b088@technikum-wien.at>
Date:
2018-03-31
Definition in file myfind.c.
Enumeration Type Documentation
enum FileTypes
Enumerator:
None
No filtering by file type.
BlockSpecialFile
Block special files should be printed.
CharacterSpecialFile
Character special files should be printed.
Directory
Directories should be printed.
NamedPipe
Named pipes should be printed.
RegularFile
Regular files should be printed.
SymbolicLink
Symbolic links should be printed.
Socket
Sockets should be printed.
Definition at line 29 of file myfind.c.
Function Documentation
struct FileNode * AddListNode (struct FileNode ** head, char * fileName) [read]
Creates a new file node and adds it to the linked list.
Parameters:
head A pointer to the head of the linked list into which the new node should be inserted.
fileName The file name to store in the created node.
Returns:
The created file node.
Definition at line 602 of file myfind.c.
References FileNode::fileName, and FileNode::next.
Referenced by SearchDirectory().
char * CombinePath (char * path1, char * path2)
Concatenates the provided path strings into a single path, adding or removing the intermediate directory separator as necessary.
Parameters:
path1 The first path to combine.
path2 The second path to combine.
Returns:
The combined path as a newly allocated string, which needs to be released with free().
Definition at line 535 of file myfind.c.
Referenced by SearchDirectory().
bool ConvertToInteger (char * s, int * i)
Converts the provided string to an integer.
Parameters:
s The string to convert to an integer.
i A pointer to the integer value in which to store the converted string.
Returns:
true if the string could successfully be converted to an integer value. Otherwise, false.
Definition at line 383 of file myfind.c.
Referenced by ParseCommandLineArgs().
void FreeList (struct FileNode ** head)
Frees all nodes in the provided linked list.
Parameters:
head A pointer to the head of the linked list to be freed.
Definition at line 644 of file myfind.c.
References FileNode::fileName, and FileNode::next.
Referenced by SearchDirectory().
int main (int argc, char * argv[])
The entry point of the application.
Parameters:
argc The number of command line arguments in argv.
argv The array of command line arguments. The last element of the array is NULL.
Returns:
Zero if execution was successful. -1 if an unrecoverable error occurred during execution.
Definition at line 119 of file myfind.c.
References ParseCommandLineArgs(), PrintUsage(), SearchFile(), and Args::searchPath.
bool ParseCommandLineArgs (char * argv[], struct Args * args)
Parses and validates the application's command line arguments.
Parameters:
argv The array of command line arguments. The last element in the array must be NULL.
args A pointer to the struct of processed command line arguments within which to store the parsed information.
Returns:
true if all command line arguments could be parsed successfully. Otherwise, false.
Definition at line 182 of file myfind.c.
References ConvertToInteger(), Args::fileTypes, Args::filterByFileType, Args::filterByUserID, Args::filterForNamePattern, Args::filterForNoUser, Args::filterForPathPattern, Args::namePattern, ParseFileTypes(), Args::pathPattern, Args::printInExtendedFormat, QueryUserID(), Args::searchPath, and Args::userID.
Referenced by main().
bool ParseFileTypes (char * fileTypeChars, enum FileTypes * fileTypes)
Parses the string that specifies the file types to be printed.
Parameters:
fileTypeChars The array of characters representing the file types to be printed.
fileTypes A pointer to the enumeration value in which to store the parsed information.
Returns:
true if all file type characters could be parsed successfully. Otherwise, false.
Definition at line 326 of file myfind.c.
References BlockSpecialFile, CharacterSpecialFile, Directory, NamedPipe, None, RegularFile, Socket, and SymbolicLink.
Referenced by ParseCommandLineArgs().
void PrintFileInformation (char * filePath, struct stat * fileInformation, struct Args * args)
Prints the information of a single file or directory.
Parameters:
filePath The path of the file to be printed.
fileInformation The information of the file as returned by stat().
args The command line options that specify the format in which to print the file's information.
Returns:
The created file node.
Definition at line 725 of file myfind.c.
References Args::printInExtendedFormat.
Referenced by SearchFile().
void PrintUsage ()
Definition at line 154 of file myfind.c.
Referenced by main().
bool QueryUserID (char * userName, int * userID)
Queries the user ID of the user with the specified name.
Parameters:
userName The name of the user for which to get the ID.
userID A pointer to the integer value in which to store the queries user ID.
Returns:
true if the user ID could be queried successfully. Otherwise, false.
Definition at line 392 of file myfind.c.
Referenced by ParseCommandLineArgs().
void SearchDirectory (char * directoryPath, struct Args * args)
Enumerates the files and directories below the specified directory path and prints the information of each entry according to the actions specified in args.
Parameters:
directoryPath The path of the directory to process.
args The command line options representing the actions to use for printing the information of each file or directory entry.
Definition at line 437 of file myfind.c.
References AddListNode(), CombinePath(), FileNode::fileName, FreeList(), FileNode::next, and SearchFile().
Referenced by SearchFile().
void SearchFile (char * filePath, struct Args * args)
Recursively walks through all the files and directories below the specified path and prints the information of each entry according to the actions specified in args.
Parameters:
filePath The path of the file or directory to process.
args The command line options representing the actions to use for printing the information of each file or directory entry.
Definition at line 401 of file myfind.c.
References PrintFileInformation(), SearchDirectory(), and ShouldPrintFileInformation().
Referenced by main(), and SearchDirectory().
bool ShouldPrintFileInformation (char * filePath, struct stat * fileInformation, struct Args * args)
Determines whether the file with the provided path and information should be printed based on the application's command line arguments.
Parameters:
filePath The path of the file to be printed.
fileInformation The information of the file as returned by stat().
args The command line options that specify the criteria by which to select the files to be printed.
Definition at line 669 of file myfind.c.
References BlockSpecialFile, CharacterSpecialFile, Directory, Args::fileTypes, Args::filterByFileType, Args::filterByUserID, Args::filterForNamePattern, Args::filterForNoUser, Args::filterForPathPattern, NamedPipe, RegularFile, Socket, and SymbolicLink.
Referenced by SearchFile().